"""empty message

Revision ID: 14ab9fb8f6f4
Revises: f915b23cff18
Create Date: 2020-07-16 08:18:50.346611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ab9fb8f6f4'
down_revision = 'f915b23cff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
