"""empty message

Revision ID: 1962b301c107
Revises: 654d1257b6a0
Create Date: 2020-07-16 07:53:20.317952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1962b301c107'
down_revision = '654d1257b6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'image_link')
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
