"""empty message

Revision ID: 1b443f7a9ca4
Revises: d4d3f9688d3e
Create Date: 2020-07-16 07:48:34.126887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b443f7a9ca4'
down_revision = 'd4d3f9688d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'image_link')
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
