"""empty message

Revision ID: 21264d1446e7
Revises: 2906b20bb832
Create Date: 2020-07-11 17:14:12.002364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21264d1446e7'
down_revision = '2906b20bb832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###
