"""empty message

Revision ID: 23914e4c5bb0
Revises: 502d851b0989
Create Date: 2020-07-12 11:25:27.345667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23914e4c5bb0'
down_revision = '502d851b0989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###
