"""Expanded length of genres in Venue

Revision ID: 2640c772e75b
Revises: d5feb630f87a
Create Date: 2020-07-07 07:01:35.738439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640c772e75b'
down_revision = 'd5feb630f87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows', sa.VARCHAR(length=120), nullable=True))
    op.add_column('venues', sa.Column('past_shows', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
