"""empty message

Revision ID: 2906b20bb832
Revises: ff3bccda49a1
Create Date: 2020-07-11 17:08:31.674207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2906b20bb832'
down_revision = 'ff3bccda49a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_count')
    # ### end Alembic commands ###
