"""empty message

Revision ID: 3e2be28fc9dd
Revises: 9a4554a1ff5b
Create Date: 2020-07-16 07:38:06.108300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2be28fc9dd'
down_revision = '9a4554a1ff5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
