"""empty message

Revision ID: 4433fafae510
Revises: 52d18fe999ea
Create Date: 2020-07-11 17:49:25.397048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433fafae510'
down_revision = '52d18fe999ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
