"""empty message

Revision ID: 47ae25f1b4c7
Revises: 2129515b7608
Create Date: 2020-07-05 20:23:46.376095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ae25f1b4c7'
down_revision = '2129515b7608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'start_time',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'start_time',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
