"""empty message

Revision ID: 4d3ebb801a4b
Revises: f434ffcb0f0d
Create Date: 2020-07-16 07:29:25.273533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3ebb801a4b'
down_revision = 'f434ffcb0f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
