"""empty message

Revision ID: 4d71f95cfe3c
Revises: 21264d1446e7
Create Date: 2020-07-11 17:20:34.450906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d71f95cfe3c'
down_revision = '21264d1446e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
