"""empty message

Revision ID: 502d851b0989
Revises: 8a4e65de4c23
Create Date: 2020-07-11 19:48:06.406850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d851b0989'
down_revision = '8a4e65de4c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('facebook_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'facebook_link')
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
