"""empty message

Revision ID: 52ae1fa81529
Revises: 1962b301c107
Create Date: 2020-07-16 07:53:29.197663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ae1fa81529'
down_revision = '1962b301c107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(), server_default='/static/img/default-user-icon.png', nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(), server_default='/static/img/default-venue.png', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
