"""empty message

Revision ID: 58536606e54c
Revises: db1d312c07a9
Create Date: 2020-07-16 08:12:41.983528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58536606e54c'
down_revision = 'db1d312c07a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    # ### end Alembic commands ###
