"""empty message

Revision ID: 654d1257b6a0
Revises: 1b443f7a9ca4
Create Date: 2020-07-16 07:48:43.795120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654d1257b6a0'
down_revision = '1b443f7a9ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('image_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
