"""empty message

Revision ID: 7580144b80dc
Revises: 52ae1fa81529
Create Date: 2020-07-16 07:56:06.965233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7580144b80dc'
down_revision = '52ae1fa81529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'/static/img/default-user-icon.png'::character varying"))
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(), server_default=sa.text("'/static/img/default-venue.png'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('artists', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'/static/img/default-user-icon.png'::character varying"))
    # ### end Alembic commands ###
