"""empty message

Revision ID: 761c9188154a
Revises: 5f80be322142
Create Date: 2020-07-11 17:31:24.876541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761c9188154a'
down_revision = '5f80be322142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###
