"""empty message

Revision ID: 8a4e65de4c23
Revises: faf7e265b9de
Create Date: 2020-07-11 19:14:42.296570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4e65de4c23'
down_revision = 'faf7e265b9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(), nullable=False))
    op.add_column('artists', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'image_link')
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
