"""empty message

Revision ID: 959369e0e71c
Revises: e99c341ae8e2
Create Date: 2020-07-11 16:42:38.269643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959369e0e71c'
down_revision = 'e99c341ae8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows')
    # ### end Alembic commands ###
