"""empty message

Revision ID: 9a4554a1ff5b
Revises: 5798d82d5fa5
Create Date: 2020-07-16 07:37:23.257082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4554a1ff5b'
down_revision = '5798d82d5fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
