"""empty message

Revision ID: acd7a31b7ed6
Revises: 4891ca93f448
Create Date: 2020-07-11 16:40:20.484287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd7a31b7ed6'
down_revision = '4891ca93f448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
