"""empty message

Revision ID: b6979ca198d2
Revises: a0eab00a3c41
Create Date: 2020-07-16 08:02:45.934041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6979ca198d2'
down_revision = 'a0eab00a3c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.String(), server_default='/static/img/default-venue.png', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###
