"""empty message

Revision ID: bd08c5191711
Revises: 3c00ae6dfa1b
Create Date: 2020-07-11 19:10:03.874938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd08c5191711'
down_revision = '3c00ae6dfa1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'upcoming_shows_count')
    # ### end Alembic commands ###
