"""empty message

Revision ID: db1d312c07a9
Revises: 202ffd5ff958
Create Date: 2020-07-16 08:11:43.463877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1d312c07a9'
down_revision = '202ffd5ff958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.String(), server_default='/static/img/default-venue.png', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###
