"""empty message

Revision ID: e8153d89c2fc
Revises: feaaa17954c4
Create Date: 2020-07-11 19:08:19.855331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8153d89c2fc'
down_revision = 'feaaa17954c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
