"""empty message

Revision ID: e99c341ae8e2
Revises: acd7a31b7ed6
Create Date: 2020-07-11 16:41:32.708372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c341ae8e2'
down_revision = 'acd7a31b7ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows_shows', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_shows')
    # ### end Alembic commands ###
