"""empty message

Revision ID: ea00570ce66b
Revises: 04715227b762
Create Date: 2020-07-11 18:25:30.818936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea00570ce66b'
down_revision = '04715227b762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows')
    # ### end Alembic commands ###
