"""empty message

Revision ID: f31952960ae0
Revises: 1ccd1b63c04f
Create Date: 2020-07-12 17:19:01.598197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31952960ae0'
down_revision = '1ccd1b63c04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'shows', 'venues', ['venue_name'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_name')
    # ### end Alembic commands ###
