"""empty message

Revision ID: feaaa17954c4
Revises: ea00570ce66b
Create Date: 2020-07-11 18:25:56.638266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feaaa17954c4'
down_revision = 'ea00570ce66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows')
    op.drop_column('venues', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
